name: transform
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  logger: ^2.2.0
  postgres: ^3.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
