// import 'package:transform/src/database/class/transform_database.dart';

import 'dart:convert';

import '../../transform.dart';

part 'transform_database_column_type_date_time.dart';
part 'transform_database_column_type_json.dart';
part 'transform_database_column_type_num.dart';
part 'transform_database_column_type_string.dart';

abstract class TransformDatabaseColumnType {
  TransformDatabaseColumnType();

  String asSql(TransformDatabaseType databaseType);

  bool isAutoGenerated() => false;

  dynamic convertValue(dynamic value);

  String sqlDefaultValue(TransformDatabaseType databaseType, dynamic defaultValue);
}
