part of 'transform_database_column_type.dart';

abstract class TransformDatabaseColumnTypeNum extends TransformDatabaseColumnType {
  num get minValue;
  num get maxValue;

  @override
  String sqlDefaultValue(TransformDatabaseType databaseType, dynamic defaultValue) {
    if (defaultValue == null) return "0";
    return defaultValue.toString();
  }
}

/// 1 byte
class TransformDatabaseColumnTypeBool extends TransformDatabaseColumnTypeNum {
  TransformDatabaseColumnTypeBool();

  @override
  num get minValue => 0;

  @override
  num get maxValue => 1;

  @override
  String sqlDefaultValue(TransformDatabaseType databaseType, dynamic defaultValue) {
    if (defaultValue == null) return "0";
    if (defaultValue is bool) return defaultValue ? "1" : "0";
    return defaultValue.toString();
  }

  @override
  dynamic convertValue(dynamic value) => BoolUtil.decodeNotNull(value, false);

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "smallint";
      case TransformDatabaseType.mysql:
        return "smallint";
    }
  }
}

/// 2 bytes	(-32768 to +32767)
class TransformDatabaseColumnTypeSmallInt extends TransformDatabaseColumnTypeNum {
  TransformDatabaseColumnTypeSmallInt();

  @override
  num get minValue => -32768;

  @override
  num get maxValue => 32767;

  @override
  dynamic convertValue(dynamic value) => IntUtil.decodeNotNull(value, 0);

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "smallint";
      case TransformDatabaseType.mysql:
        return "smallint";
    }
  }
}

/// 4 bytes	(-2147483648 to +2147483647)
class TransformDatabaseColumnTypeInteger extends TransformDatabaseColumnTypeNum {
  TransformDatabaseColumnTypeInteger();

  @override
  num get minValue => -2147483647;

  @override
  num get maxValue => 2147483648;

  @override
  dynamic convertValue(dynamic value) => IntUtil.decodeNotNull(value, 0);

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "integer";
      case TransformDatabaseType.mysql:
        return "int";
    }
  }
}

/// 8 bytes	(-9223372036854775808 to +9223372036854775807)
class TransformDatabaseColumnTypeBigInt extends TransformDatabaseColumnTypeNum {
  TransformDatabaseColumnTypeBigInt();

  @override
  num get minValue => -9223372036854775808;

  @override
  num get maxValue => -9223372036854775807;

  @override
  dynamic convertValue(dynamic value) => IntUtil.decodeNotNull(value, 0);

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "bigint";
      case TransformDatabaseType.mysql:
        return "bigint";
    }
  }
}

/// 2 bytes	(1 to +32767)
class TransformDatabaseColumnTypeSmallSerial extends TransformDatabaseColumnTypeNum {
  TransformDatabaseColumnTypeSmallSerial();

  @override
  num get minValue => 1;

  @override
  num get maxValue => 32768;

  @override
  dynamic convertValue(dynamic value) => IntUtil.decodeNotNull(value, 0);

  @override
  bool isAutoGenerated() => true;

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "smallserial";
      case TransformDatabaseType.mysql:
        return "smallint unsigned not null auto_increment unique";
    }
  }
}

/// 4 bytes	(1 to +2147483647)
class TransformDatabaseColumnTypeSerial extends TransformDatabaseColumnTypeNum {
  TransformDatabaseColumnTypeSerial();

  @override
  num get minValue => 1;

  @override
  num get maxValue => 2147483647;

  @override
  dynamic convertValue(dynamic value) => IntUtil.decodeNotNull(value, 0);

  @override
  bool isAutoGenerated() => true;

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "serial";
      case TransformDatabaseType.mysql:
        return "int unsigned not null auto_increment unique";
    }
  }
}

/// 8 bytes	(1 to +9223372036854775807)
class TransformDatabaseColumnTypeBigSerial extends TransformDatabaseColumnTypeNum {
  TransformDatabaseColumnTypeBigSerial();

  @override
  num get minValue => 1;

  @override
  num get maxValue => 9223372036854775807;

  @override
  dynamic convertValue(dynamic value) => IntUtil.decodeNotNull(value, 0);

  @override
  bool isAutoGenerated() => true;

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "bigserial";
      case TransformDatabaseType.mysql:
        return "bigint unsigned not null auto_increment unique";
    }
  }
}

/// variable bytes (depends of precision)
class TransformDatabaseColumnTypeDecimal extends TransformDatabaseColumnTypeNum {
  final int precision;
  final int scale;
  TransformDatabaseColumnTypeDecimal({this.precision = 20, this.scale = 6}) {
    assert(precision > 0);
    assert(scale >= 0);
    assert(scale <= precision);
  }

  @override
  num get maxValue => 10 ^ precision - 10 ^ -scale;

  @override
  num get minValue => -10 ^ precision + 10 ^ -scale;

  @override
  dynamic convertValue(dynamic value) => DoubleUtil.decodeNotNull(value, 0);

  @override
  String asSql(TransformDatabaseType databaseType) {
    switch (databaseType) {
      case TransformDatabaseType.postgres:
        return "decimal($precision, $scale)";
      case TransformDatabaseType.mysql:
        return "decimal($precision, $scale)";
    }
  }
}

/// variable bytes (precision: 20, scale: 2)
class TransformDatabaseColumnTypeMonetary extends TransformDatabaseColumnTypeDecimal {
  TransformDatabaseColumnTypeMonetary() : super(precision: 20, scale: 2);
}
